export type {
  ExtensionModule,
  ExtensionContext,
  ExtensionManifest,
  ExtensionContributions,
  CommandContribution,
  ViewContribution,
  TerminalMindAPI,
  CommandsNamespace,
  ViewsNamespace,
  EventsNamespace,
  SidebarViewProvider,
} from './extension-api';

export { IpcChannels, IpcEventChannels } from './ipc/index';
export type {
  TerminalCreateOptions,
  TerminalSessionInfo,
  ShellInfo,
  CommandInfo,
  SSHAuthMethod,
  SSHConnectOptions,
  SSHSessionInfo,
  ExecResult,
  PortForwardOptions,
  PortForwardInfo,
  SFTPFileStat,
  SFTPFileEntry,
  SFTPTransferOptions,
  SFTPTransferResult,
  SFTPTransferProgress,
  SFTPQueueTaskInfo,
  LocalDirEntry,
  ConnectionProfileTimestamps,
  ConnectionProfile,
  ConnectionStoreChangeEvent,
  HostKeyPromptPayload,
  SSHStatusChangePayload,
  PtyDataPayload,
  PtyInputPayload,
  EventBroadcastPayload,
  PreloadAPI,
} from './ipc/index';
