export const IpcChannels = {
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_DESTROY: 'terminal:destroy',
  TERMINAL_LIST: 'terminal:list',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_GET_SESSION: 'terminal:getSession',
  SHELL_DISCOVER: 'shell:discover',
  SHELL_GET_DEFAULT: 'shell:getDefault',
  COMMAND_EXECUTE: 'command:execute',
  COMMAND_LIST: 'command:list',
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  SSH_CONNECT: 'ssh:connect',
  SSH_DISCONNECT: 'ssh:disconnect',
  SSH_LIST_SESSIONS: 'ssh:listSessions',
  SSH_GET_SESSION: 'ssh:getSession',
  SSH_EXEC: 'ssh:exec',
  SSH_FORWARD_PORT: 'ssh:forwardPort',
  SSH_CLOSE_FORWARD: 'ssh:closeForward',
  SSH_LIST_FORWARDS: 'ssh:listForwards',
  SSH_HOST_KEY_VERIFY: 'ssh:hostKeyVerify',
  SSH_HOST_KEY_ACCEPT: 'ssh:hostKeyAccept',
  SFTP_LIST: 'sftp:list',
  SFTP_STAT: 'sftp:stat',
  SFTP_MKDIR: 'sftp:mkdir',
  SFTP_RMDIR: 'sftp:rmdir',
  SFTP_UNLINK: 'sftp:unlink',
  SFTP_RENAME: 'sftp:rename',
  SFTP_UPLOAD: 'sftp:upload',
  SFTP_DOWNLOAD: 'sftp:download',
  SFTP_CANCEL_TRANSFER: 'sftp:cancelTransfer',
  SFTP_RETRY_TRANSFER: 'sftp:retryTransfer',
  SFTP_LIST_TRANSFERS: 'sftp:listTransfers',
  SFTP_CLEAR_COMPLETED: 'sftp:clearCompleted',
  CONNECTIONS_LIST: 'connections:list',
  CONNECTIONS_GET: 'connections:get',
  CONNECTIONS_SAVE: 'connections:save',
  CONNECTIONS_REMOVE: 'connections:remove',
  CONNECTIONS_IMPORT: 'connections:import',
  CONNECTIONS_EXPORT: 'connections:export',
} as const;

export const IpcEventChannels = {
  PTY_DATA: 'pty:data',
  PTY_INPUT: 'pty:input',
  EVENT_BROADCAST: 'event:broadcast',
  SSH_STATUS_CHANGE: 'ssh:statusChange',
  SSH_HOST_KEY_PROMPT: 'ssh:hostKeyPrompt',
  SSH_PASSWORD_PROMPT: 'ssh:passwordPrompt',
  SFTP_TRANSFER_PROGRESS: 'sftp:transferProgress',
  SFTP_TRANSFER_COMPLETE: 'sftp:transferComplete',
  CONNECTION_CHANGED: 'connection:changed',
} as const;
